version: '3.8'

services:
  app:
    image: node:22.14.0
    container_name: meetpoint-backend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017/meetpoint
      - FIREBASE_SERVICE_ACCOUNT_KEY=/app/serviceAccountKey.json
      - FIREBASE_DATABASE_URL=https://your_project_id.firebaseio.com
    depends_on:
      - db
    command: ["npm", "run", "start"]

  db:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=meetpoint

volumes:
  mongo-data:
